import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

const root = process.cwd();

const sourceFiles = (dir: string): string[] =>
  readdirSync(resolve(root, dir), { withFileTypes: true }).flatMap(entry => {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory()) return sourceFiles(path);
    return /\.tsx?$/.test(entry.name) ? [path] : [];
  });

const read = (file: string) => readFileSync(resolve(root, file), 'utf8');

describe('QR codes are drawn on the device', () => {
  /**
   * The TON deposit QR was an `<img>` pointing at api.qrserver.com — the code a
   * player scans to send real money was generated by a third party. Whoever
   * serves that image decides what it encodes, and a swapped address looks
   * identical to the eye. The same request also had to leave the Telegram
   * webview at all, so a slow or blocked host meant no QR.
   */
  it('never asks a remote service to render one', () => {
    const offenders = sourceFiles('src').filter(file =>
      /qrserver|chart\.googleapis\.com\/chart|qrcode\.tec-it|goqr\.me/i.test(read(file))
    );
    expect(offenders).toEqual([]);
  });

  it('recognises the shape it forbids', () => {
    // Otherwise the sweep passes whether the app is clean or the pattern simply
    // stopped matching.
    expect(/qrserver/i.test('https://api.qrserver.com/v1/create-qr-code/?data=x')).toBe(true);
  });

  it('renders the deposit code through the local component', () => {
    const modal = read('src/components/pages/out-tabs/drawer/wallet/DepositTonModal.tsx');
    expect(modal).toContain("import { QrCode } from '@/components/shared/QrCode'");
    expect(modal).toMatch(/<QrCode\b/);
  });

  /**
   * A QR is unreadable without contrast and a quiet zone, and this one sits on
   * a dark themed sheet — styling it to match would make it pretty and
   * unscannable.
   */
  it('keeps the code black on white with a quiet zone', () => {
    const qr = read('src/components/shared/QrCode.tsx');
    expect(qr).toContain('#ffffff');
    expect(qr).toContain('#000000');
    expect(qr).toMatch(/quiet\s*=\s*4/);
  });
});
