export const rtkTags = {
  me: 'Me',
  tournaments: 'Tournaments',
  tournamentById: ':TournamentById',
  tickets: 'Tickets',
  engines: 'Engines',
  tasks: 'Tasks',
  leaderboard: 'Leaderboard',
  jackpot: 'Jackpot',
  faq: 'Faq',
  privacy: 'Privacy',
  notifications: 'Notifications',
  notificationPreferences: 'NotificationPreferences',
  referral: 'Referral',
  market: 'Market',
  stakes: 'Stakes',
  wallet: 'Wallet',
  walletTransactions: 'WalletTransactions',
  starsPackages: 'StarsPackages',
  lc: 'Lc',
  lcTransactions: 'LcTransactions',
  achievements: 'Achievements',
  profile: 'Profile',
  profileById: ':ProfileById',
  inventory: 'Inventory',
  avatars: 'Avatars',
  partnerStats: 'PartnerStats',
} as const;
