export const rtkTags = {
  me: 'Me',
  tournaments: 'Tournaments',
  tournamentById: ':TournamentById',
  tickets: 'Tickets',
  engines: 'Engines',
  tasks: 'Tasks',
  leaderboard: 'Leaderboard',
  support: 'Support',
  notifications: 'Notifications',
  notificationPreferences: 'NotificationPreferences',
  referral: 'Referral',
  exchange: 'Exchange',
  market: 'Market',
  stakes: 'Stakes',
  wallet: 'Wallet',
  walletTransactions: 'WalletTransactions',
  starsPackages: 'StarsPackages',
  achievements: 'Achievements',
  profile: 'Profile',
  profileById: ':ProfileById',
  inventory: 'Inventory',
  avatars: 'Avatars',
} as const;
